import { Montserrat } from 'next/font/google'
import './globals.css'
import HeaderPage from './components/HeaderPage'

const montserrat = Montserrat({ subsets: ['cyrillic'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <HeaderPage />
        <main>
         {children}
        </main>
      </body>
    </html>
  )
}
